name: Docker

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get tag
      id: repository
      run: echo "tag=$(git describe --tags HEAD)" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: zivillian/lotus2mqtt
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: zivillian/lotus2mqtt:main
        labels: ${{ steps.meta.outputs.labels }}